"""Upload benchmark results to the leaderboard via GitHub."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

from claw_bench.submission.packager import validate_package


def gh_available() -> bool:
    """Check whether the ``gh`` CLI tool is installed."""
    return shutil.which("gh") is not None


def submit_pr(results_dir: Path, repo: str, name: str) -> str:
    """Fork *repo*, create a branch, commit results, and open a PR.

    Uses the ``gh`` CLI tool for GitHub operations.
    Returns the URL of the created pull request.

    Raises:
        ValueError: If the results package is invalid.
        RuntimeError: If ``gh`` is not installed or a git operation fails.
        NotImplementedError: If ``gh`` is not available.
    """
    results_dir = Path(results_dir)
    if not validate_package(results_dir):
        raise ValueError(
            "Results package is invalid or missing manifest. "
            "Run package_results() first."
        )

    if not gh_available():
        raise NotImplementedError(
            "GitHub PR submission requires the 'gh' CLI tool. "
            "Install from https://cli.github.com/"
        )

    # Check gh auth status
    auth_check = subprocess.run(
        ["gh", "auth", "status"],
        capture_output=True,
        text=True,
        timeout=10,
    )
    if auth_check.returncode != 0:
        raise RuntimeError("Not authenticated with GitHub. Run 'gh auth login' first.")

    # Fork the repo (idempotent)
    subprocess.run(
        ["gh", "repo", "fork", repo, "--clone=false"],
        capture_output=True,
        text=True,
        timeout=30,
    )

    # Clone the fork
    import tempfile

    work_dir = Path(tempfile.mkdtemp(prefix="claw-bench-submit-"))
    clone_result = subprocess.run(
        ["gh", "repo", "clone", repo, str(work_dir / "repo"), "--", "--depth=1"],
        capture_output=True,
        text=True,
        timeout=60,
    )
    if clone_result.returncode != 0:
        raise RuntimeError(f"Failed to clone repo: {clone_result.stderr}")

    repo_dir = work_dir / "repo"
    branch_name = f"submit/{name}"

    # Create branch
    subprocess.run(
        ["git", "checkout", "-b", branch_name],
        cwd=repo_dir,
        capture_output=True,
        timeout=10,
    )

    # Copy results into the repo
    import shutil as sh

    dest = repo_dir / "submissions" / name
    dest.mkdir(parents=True, exist_ok=True)
    for f in results_dir.rglob("*"):
        if f.is_file():
            rel = f.relative_to(results_dir)
            target = dest / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            sh.copy2(f, target)

    # Commit
    subprocess.run(["git", "add", "."], cwd=repo_dir, capture_output=True, timeout=10)
    subprocess.run(
        ["git", "commit", "-m", f"Add benchmark results: {name}"],
        cwd=repo_dir,
        capture_output=True,
        timeout=10,
    )

    # Push and create PR
    subprocess.run(
        ["git", "push", "-u", "origin", branch_name],
        cwd=repo_dir,
        capture_output=True,
        timeout=30,
    )

    pr_result = subprocess.run(
        [
            "gh",
            "pr",
            "create",
            "--title",
            f"Benchmark submission: {name}",
            "--body",
            f"Automated benchmark result submission for **{name}**.\n\nGenerated by `claw-bench submit`.",
            "--repo",
            repo,
        ],
        cwd=repo_dir,
        capture_output=True,
        text=True,
        timeout=30,
    )
    if pr_result.returncode != 0:
        raise RuntimeError(f"Failed to create PR: {pr_result.stderr}")

    # Clean up work dir
    sh.rmtree(work_dir, ignore_errors=True)

    return pr_result.stdout.strip()


def submit_api(results_dir: Path, server_url: str = "https://clawbench.net", claw_id: str | None = None, custom_name: str | None = None) -> str:
    """Submit results via the public API endpoint.

    Reads leaderboard.json (preferred) or summary.json, extracts scores,
    and POSTs to the server's /api/submit endpoint.
    """
    import hashlib
    import json
    import platform
    import uuid

    results_dir = Path(results_dir)

    manifest_exists = (results_dir / "manifest.sha256").exists()
    if manifest_exists and not validate_package(results_dir):
        raise ValueError("Results package integrity check failed.")

    for candidate in ("leaderboard.json", "summary.json", "results.json"):
        f = results_dir / candidate
        if f.exists():
            results_file = f
            break
    else:
        raise FileNotFoundError(
            f"No results file found in {results_dir}. "
            "Expected leaderboard.json, summary.json, or results.json."
        )

    data = json.loads(results_file.read_text())
    if isinstance(data, list):
        data = data[0] if data else {}

    fp_raw = f"{platform.node()}:{platform.machine()}:{uuid.getnode()}"
    fingerprint = hashlib.sha256(fp_raw.encode()).hexdigest()

    scores = data.get("scores", {})

    payload = {
        "framework": data.get("framework", "unknown"),
        "model": data.get("model", "unknown"),
        "overall": data.get("overall", scores.get("overall", 0)),
        "taskCompletion": data.get("taskCompletion", scores.get("task_completion", 0)),
        "efficiency": data.get("efficiency", scores.get("efficiency", 0)),
        "security": data.get("security", scores.get("security", 0)),
        "skills": data.get("skills", data.get("skills_efficacy", scores.get("skills_efficacy", 0))),
        "ux": data.get("ux", data.get("ux_engineering", scores.get("ux_engineering", 0))),
        "testTier": data.get("testTier", data.get("test_tier")),
        "fingerprint": fingerprint,
        "tasksCompleted": data.get("tasksCompleted", scores.get("tasks_total", data.get("tasks_completed"))),
    }

    profile = data.get("agentProfile") or data.get("agent_profile")
    if profile:
        payload["agentProfile"] = {
            "displayName": profile.get("displayName", profile.get("display_name", "")),
            "model": profile.get("model", payload["model"]),
            "framework": profile.get("framework", payload["framework"]),
            "skillsMode": profile.get("skillsMode", profile.get("skills_mode", "vanilla")),
            "skills": profile.get("skills", []),
            "mcpServers": profile.get("mcpServers", profile.get("mcp_servers", [])),
            "memoryModules": profile.get("memoryModules", profile.get("memory_modules", [])),
            "modelTier": profile.get("modelTier", profile.get("model_tier")),
        }

    if data.get("progressive"):
        payload["progressive"] = data["progressive"]

    if claw_id:
        payload["clawId"] = claw_id
    if custom_name:
        payload["customName"] = custom_name

    raw_task_results = data.get("task_results", data.get("taskDetails", []))
    if raw_task_results:
        task_items = []
        for tr in raw_task_results:
            tid = tr.get("task_id", tr.get("taskId", ""))
            passed = tr.get("passed", False)
            score = tr.get("score", 1.0 if passed else 0.0)
            if tid:
                task_items.append({"taskId": tid, "passed": bool(passed), "score": float(score)})
        if task_items:
            payload["taskResults"] = task_items

    payload["rawSummary"] = data

    metadata = data.get("metadata", {})
    total_tokens_in = metadata.get("total_tokens_input", 0)
    total_tokens_out = metadata.get("total_tokens_output", 0)
    if not total_tokens_in:
        for tr in raw_task_results:
            total_tokens_in += tr.get("tokens_input", tr.get("tokensInput", 0)) or 0
            total_tokens_out += tr.get("tokens_output", tr.get("tokensOutput", 0)) or 0
    if total_tokens_in or total_tokens_out:
        payload["tokensCost"] = round((total_tokens_in * 0.01 + total_tokens_out * 0.03) / 1000, 4)

    import httpx

    url = f"{server_url.rstrip('/')}/api/submit"
    resp = httpx.post(url, json=payload, timeout=30)

    if resp.status_code == 200:
        result = resp.json()
        rank = result.get("rank", "?")
        total = result.get("totalEntries", "?")
        tier = result.get("testTier", "")
        tier_rank = result.get("tierRank", 0)
        tier_total = result.get("tierTotal", 0)
        lines = [f"Now live on the leaderboard! Global rank: #{rank} of {total}"]
        if tier_rank and tier_total:
            lines.append(f"{tier} tier rank: #{tier_rank} of {tier_total}")
        lines.append(f"View at: https://clawbench.net")
        return "\n".join(lines)
    elif resp.status_code == 409:
        return "Duplicate: identical results already exist on the leaderboard."
    elif resp.status_code == 429:
        detail = resp.json().get("detail", "Rate limited.")
        raise RuntimeError(f"Rate limited: {detail}")
    else:
        detail = resp.json().get("detail", resp.text)
        raise RuntimeError(f"Submission failed ({resp.status_code}): {detail}")


def submit_dry_run(results_dir: Path) -> None:
    """Validate the package and print what *submit_pr* would do."""
    results_dir = Path(results_dir)
    is_valid = validate_package(results_dir)

    print(f"Results directory: {results_dir}")
    print(f"Package valid:     {is_valid}")

    if not is_valid:
        print("ERROR: package validation failed; fix before submitting.")
        return

    files = sorted(
        str(p.relative_to(results_dir)) for p in results_dir.rglob("*") if p.is_file()
    )
    print(f"Files to upload:   {len(files)}")
    for f in files:
        print(f"  - {f}")
    print(f"\nGitHub CLI:        {'available' if gh_available() else 'NOT FOUND'}")
    print("Dry run complete. No changes were made.")
